[theme]

#919e8b
primaryColor = "#229e6b" # green

backgroundColor = "rgba(254,248,239,1)" # sepia yellow

secondaryBackgroundColor =  "#ebd2b9" # wheat  "#f8eed5" # yellow <-- not enough contrast

#d7ab82
textColor = "#6e7074" # grey

font = "sans serif"